[tool.poetry]
name = "seed"
version = "0.1.0"
description = "Writer helper"
authors = ["codenomad <codenomad@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.9.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pyright = "^1.1.379"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
addopts = "--cov=seed"
markers = ["asset: Asset model tests", "descriptor: Descriptor model tests", "wip: work in progress tests"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
fail_under = 80
show_missing = true
